name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on changes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub username stored in secrets
          password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub password (or token) stored in secrets

      # Build and push Docker image
      - name: Build and push Docker image
        run: |
          docker build -t myapp .  # Replace "myapp" with your app's name or desired tag
          docker tag myapp:latest ${{ secrets.DOCKER_USERNAME }}/myapp:latest  # Tagging image
          docker push ${{ secrets.DOCKER_USERNAME }}/myapp:latest  # Pushing image to Docker Hub
