name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # This triggers the pipeline on changes to the main branch.
  pull_request:
    branches:
      - main  # This triggers the pipeline on pull requests to the main branch.

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Correctly referencing the secret for Docker username
          password: ${{ secrets.DOCKER_PASSWORD }}  # Correctly referencing the secret for Docker password

      - name: Build and push Docker image
        run: |
          docker build -t myapp .
          docker tag myapp:latest ${{ secrets.DOCKER_USERNAME }}/myapp:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/myapp:latest
